### ISSUE TITLE
Please Update to 2.2 because 1.12 is out

### ISSUE THREAD

**Issue by Tzzzt123** [lenis0012/LoginSecurity-2#106]
Thanks for updating soon.

**Comment by Tzzzt123** [comment]
@lenis0012 when will u answer the freaking threads

**Comment by swordin** [comment]
+1

**Comment by lenis0012** [comment]
I am releasing a version 2.1.7 @Tzzzt123 @swordin 

It has a hotfix for 1.12 support

**Comment by Tzzzt123** [comment]
@lenis0012 will u update to 2.2 in the next Month?

**Comment by swordin** [comment]
Thank you very much! The ice has broken! )

**Comment by lenis0012** [comment]
@Tzzzt123 I hope so.
I am still reworking the database engine, once that's done and tested I will be able to rapidly add in the remaining features.

After that I will need some help testing the new version to make sure it is bug free.

**Comment by Tzzzt123** [comment]
ok @lenis0012

**Comment by Tzzzt123** [comment]
@lenis0012 please tell me when 2.2 is out.

**Comment by swordin** [comment]
+1

I can't watch the registration and login bugs anymore...

**Comment by Tzzzt123** [comment]
@swordin i am only waiting for the new features, i don't have so many bugs at the moment

**Comment by swordin** [comment]
but my problem is that: /reg and /l do not work (((

**Comment by Tzzzt123** [comment]
ok @swordin lets hope its out till end of june

**Comment by swordin** [comment]
I pray for it to happen

**Comment by Alvaroctal** [comment]
```
[00:04:03] [Server thread/ERROR]: Error occurred while enabling LoginSecurity v2.1.7 (Is it up to date?)
java.lang.IllegalArgumentException: duration cannot be negative: -1 SECONDS
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:335) ~[spigot.jar:git-Spigot-0869666-03f1e37]
        at com.google.common.cache.CacheBuilder.expireAfterWrite(CacheBuilder.java:626) ~[spigot.jar:git-Spigot-0869666-03f1e37]
        at com.lenis0012.bukkit.loginsecurity.modules.threading.ThreadingModule.reload(ThreadingModule.java:54) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.modules.threading.ThreadingModule.enable(ThreadingModule.java:37) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-0869666-03f1e37]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-0869666-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-0869666-03f1e37]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-0869666-03f1e37]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-0869666-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-0869666-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-0869666-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-0869666-03f1e37]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-0869666-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-0869666-03f1e37]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

It's being printed with every server start, doesn't seems to be important, but maybe should be fixed.

**Comment by lenis0012** [comment]
@Alvaroctal I am assuming you set session-timeout to -1 or something like that.
If you want it to be infinite, which i do not recommend, just set it to really high number like 1 million.

(don't go too high, as there is a maximum)

**Comment by Tzzzt123** [comment]
@lenis0012 when does it come out?

**Comment by swordin** [comment]
Hello,
How to export LoginSecurity DB back to the AuthMe?
I'm tired of waiting for 2.2 with bugfixing ((((( 
I can't wait anymore... It's been 6 months since I wrote about the problems... (

**Comment by ljacqu** [comment]
@swordin [`/authme converter loginsecurity`](https://github.com/AuthMe/AuthMeReloaded/wiki/Converters)

**Comment by lenis0012** [comment]
@swordin As mentioned above by @ljacqu , you can easily convert from loginsecurity to AuthMe Reloaded.

I am terribly sorry for taking forever with the next big update, and falling months behind the planned release date.

I made some poor decisions with the database rewrite that were intended to massively improve performance and ease of use, but it kind of backfired.
I am slowly going back redoing this, and I seriously expect the new version to be out in a week or two.

**Comment by swordin** [comment]
Thank you for your prompt response! If it takes a week or two to do this, I will wait. Thank you and God help you!

**Comment by lenis0012** [comment]
@swordin Would you be interested in testing the early versions?
It will save me a lot of time when working on the next version.

**Comment by swordin** [comment]
Well, I have over 20 thousand players. I'm ready to test if the risks are small and if I do not get unrecoverable problems )

**Comment by lenis0012** [comment]
@swordin Yeah, I wouldn't advise running it on a live server.
Just a local test server, or if necessary on a server that I provide.

**Comment by swordin** [comment]
I'm happy to take part in the testing. It will be better if it will be server that you provide. 
Let's exchange emails / skype-ids or something like this?

**Comment by lenis0012** [comment]
@swordin Sure.
You can add me on skype as ghost.nl2
Or on discord as lenis#4331

**Comment by swordin** [comment]
skype is good

done )

**Comment by lenis0012** [comment]
Version 3.0.0 has entered alpha stage.
I think we can close this issue
