### ISSUE TITLE
FIX PLS: Internal server error for URL: http://lang.lenis0012.com/language/ru_ru

### ISSUE THREAD

**Issue by swordin** [lenis0012/LoginSecurity-2#110]
Server returned HTTP response code: 500 for URL: http://lang.lenis0012.com/language/ru_ru

[00:33:25] [Server thread/INFO]: [LoginSecurity] Loading base translations from "en_us"
[00:33:25] [Server thread/INFO]: [LoginSecurity] Loading specified translations from "ru_ru"
[00:33:25] [Server thread/WARN]: [LoginSecurity] Couldn't get translation, defaulting to en_us
java.io.IOException: Server returned HTTP response code: 500 for URL: http://lang.lenis0012.com/language/ru_ru
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_131]
        at com.lenis0012.bukkit.loginsecurity.modules.language.LanguageAPI.apiRequest(LanguageAPI.java:61) ~[LoginSecurity.jar:git-LoginSecurity-4709b9e]
        at com.lenis0012.bukkit.loginsecurity.modules.language.LanguageAPI.getTranslation(LanguageAPI.java:47) ~[LoginSecurity.jar:git-LoginSecurity-4709b9e]

        at com.lenis0012.bukkit.loginsecurity.modules.language.LanguageModule.enable(LanguageModule.java:34) [LoginSecurity.jar:git-LoginSecurity-4709b9e]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) [LoginSecurity.jar:git-LoginSecurity-4709b9e]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) [LoginSecurity.jar:git-LoginSecurity-4709b9e]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) [LoginSecurity.jar:git-LoginSecurity-4709b9e]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by lenis0012** [comment]
I resolved the issue
