### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by vanjmali** [lenis0012/LoginSecurity-2#130]
`[WARNING] Exception in thread "pool-85-thread-10" 
[WARNING] java.lang.IllegalStateException: Asynchronous player tracker clear! 
[WARNING] at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) 
[WARNING] at net.minecraft.server.v1_13_R2.EntityTrackerEntry.clear(EntityTrackerEntry.java:571) 
[WARNING] at net.minecraft.server.v1_13_R2.EntityTracker.untrackPlayer(EntityTracker.java:239) 
[WARNING] at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:587) 
[WARNING] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:624) 
[WARNING] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:295) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.AuthAction.rehabPlayer(AuthAction.java:71) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.action.LoginAction.run(LoginAction.java:23) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:168) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:142) 
[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
[WARNING] at java.lang.Thread.run(Thread.java:813) `

This probably happen because I reloaded the server, but it wasn't doing that before.
it seems like the player cannot be found after the login session.

I will try restarting the server, but I just wanted to report this if this could be fixed in future.

**Comment by vanjmali** [comment]
> [WARNING] Exception in thread "pool-7-thread-1" 
[WARNING] java.lang.IllegalStateException: Asynchronous player tracker clear! 
[WARNING] at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) 
[WARNING] at net.minecraft.server.v1_13_R2.EntityTrackerEntry.clear(EntityTrackerEntry.java:571) 
[WARNING] at net.minecraft.server.v1_13_R2.EntityTracker.untrackPlayer(EntityTracker.java:239) 
[WARNING] at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:587) 
[WARNING] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:624) 
[WARNING] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:295) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.AuthAction.rehabPlayer(AuthAction.java:71) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.action.LoginAction.run(LoginAction.java:23) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:168) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:142) 
[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
[WARNING] at java.lang.Thread.run(Thread.java:813) 
[WARNING] Exception in thread "pool-7-thread-2" 
[WARNING] java.lang.IllegalStateException: Asynchronous player tracker clear! 
[WARNING] at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) 
[WARNING] at net.minecraft.server.v1_13_R2.EntityTrackerEntry.clear(EntityTrackerEntry.java:571) 
[WARNING] at net.minecraft.server.v1_13_R2.EntityTracker.untrackPlayer(EntityTracker.java:239) 
[WARNING] at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:587) 
[WARNING] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:624) 
[WARNING] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:295) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.AuthAction.rehabPlayer(AuthAction.java:71) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.action.LoginAction.run(LoginAction.java:23) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:168) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:142) 
[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
[WARNING] at java.lang.Thread.run(Thread.java:813) 
[WARNING] Exception in thread "pool-7-thread-3" 
[WARNING] java.lang.IllegalStateException: Asynchronous player tracker clear! 
[WARNING] at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) 
[WARNING] at net.minecraft.server.v1_13_R2.EntityTrackerEntry.clear(EntityTrackerEntry.java:571) 
[WARNING] at net.minecraft.server.v1_13_R2.EntityTracker.untrackPlayer(EntityTracker.java:239) 
[WARNING] at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:587) 
[WARNING] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:624) 
[WARNING] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:295) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.AuthAction.rehabPlayer(AuthAction.java:71) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.action.LoginAction.run(LoginAction.java:23) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:168) 
[WARNING] at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:142) 
[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
[WARNING] at java.lang.Thread.run(Thread.java:813) 
>
still cannot log in... even when I restart it, but it shows a different error..
