### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by M0dii** [lenis0012/LoginSecurity-2#143]
```
26.05 23:54:04 [Server] ERROR [LoginSecurity] Failed to save user profile
26.05 23:54:04 [Server] INFO org.sqlite.SQLiteException: [SQLITE_READONLY] Attempt to write a readonly database (attempt to write a readonly database)
26.05 23:54:04 [Server] INFO at org.sqlite.core.DB.newSQLException(DB.java:941) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.sqlite.core.DB.newSQLException(DB.java:953) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.sqlite.core.DB.execute(DB.java:857) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.sqlite.core.DB.executeUpdate(DB.java:895) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at com.lenis0012.bukkit.loginsecurity.database.ProfileRepository.updateBlocking(ProfileRepository.java:70) ~[?:?]
26.05 23:54:04 [Server] INFO at com.lenis0012.bukkit.loginsecurity.database.ProfileRepository.lambda$update$1(ProfileRepository.java:56) ~[?:?]
26.05 23:54:04 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
26.05 23:54:04 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
26.05 23:54:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
26.05 23:54:04 [Server] ERROR [LoginSecurity] Failed to save user profile
26.05 23:54:04 [Server] INFO org.sqlite.SQLiteException: [SQLITE_READONLY] Attempt to write a readonly database (attempt to write a readonly database)
26.05 23:54:04 [Server] INFO at org.sqlite.core.DB.newSQLException(DB.java:941) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.sqlite.core.DB.newSQLException(DB.java:953) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.sqlite.core.DB.execute(DB.java:857) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.sqlite.core.DB.executeUpdate(DB.java:895) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at com.lenis0012.bukkit.loginsecurity.database.ProfileRepository.updateBlocking(ProfileRepository.java:70) ~[?:?]
26.05 23:54:04 [Server] INFO at com.lenis0012.bukkit.loginsecurity.database.ProfileRepository.lambda$update$1(ProfileRepository.java:56) ~[?:?]
26.05 23:54:04 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.1.jar:git-Paper-43]
26.05 23:54:04 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
26.05 23:54:04 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
26.05 23:54:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

Paper-43 Build, 1.14.1.

![image](https://user-images.githubusercontent.com/11699611/58387632-609e4180-801a-11e9-93ea-29c80ce44b85.png)

**Comment by lenis0012** [comment]
The database is in read-only mode.
This can be caused by multiple servers reading from the same file. this is not possible.

**Comment by lenis0012** [comment]
@M0dii If you want to use the same file on multiple servers, use MySQL.
Otherwise, please try restarting your computer (on which the server is running) and see if the issue persists.
