### ISSUE TITLE
Java NullPointerException

### ISSUE THREAD

**Issue by RedBlaze42** [lenis0012/LoginSecurity-2#145]
I have a error on the task 70:

```
[16:27:39] [Server thread/WARN]: [LoginSecurity] Task #70 for LoginSecurity v2.1.9 generated an exception
java.lang.NullPointerException: null
        at com.lenis0012.bukkit.loginsecurity.modules.threading.TimeoutTask.run(TimeoutTask.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by lenis0012** [comment]
Thanks for reporting I will investigate the issue
