### ISSUE TITLE
Plugin ERRORS OUT  when setting session or login timeout to -1

### ISSUE THREAD

**Issue by J-eremy** [lenis0012/LoginSecurity-2#147]
Server:  Paper Spigot
Version: git-Paper-96
NO OTHER PLUGINS

I'm trying to set my server for registration and login to be optional and it works well for the most part, except when I use a portal to go to my creative server and return.  I have been trying to set these options as outlined in the config so neither my session nor login timeout which would solve that problem entirely

'#' Session timeout in seconds, set to -1 to disable.
session-timeout: -1
'#' Login timeout in seconds, set to -1 to disable.
login-timeout: -1

Above I had to put the comment marker in quotes because of formatting, it is not like that in my config. 

Below is the error message I'm getting, its stating that the seconds can not be a negative and failing to load the plugin.

To recreate it just install the plugin and try to set the session or login timeout to -1

`[22:55:03 ERROR]: Error occurred while enabling LoginSecurity v3.0.2-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: duration cannot be negative: -1 SECONDS
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:335) ~[patched_1.14.2.jar:git-Paper-96]
        at com.google.common.cache.CacheBuilder.expireAfterWrite(CacheBuilder.java:626) ~[patched_1.14.2.jar:git-Paper-96]
        at com.lenis0012.bukkit.loginsecurity.modules.threading.ThreadingModule.reload(ThreadingModule.java:60) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.modules.threading.ThreadingModule.enable(ThreadingModule.java:38) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.2.jar:git-Paper-96]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.2.jar:git-Paper-96]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-96]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-96]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:465) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.2.jar:git-Paper-96]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:856) ~[patched_1.14.2.jar:git-Paper-96]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by lenis0012** [comment]
I see.
That's a bug.
