### ISSUE TITLE
Failed to register user

### ISSUE THREAD

**Issue by mqnoy** [lenis0012/LoginSecurity-2#169]
```
[pool-4-thread-1/ERROR]: [LoginSecurity] Failed to register user
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'uuid_mode' in 'field list'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[server.jar:git-Bukkit-3e3818b]
        at com.mysql.jdbc.jdbc2.optional.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:543) ~[server.jar:git-Bukkit-3e3818b]
        at com.lenis0012.bukkit.loginsecurity.database.ProfileRepository.insertBlocking(ProfileRepository.java:41) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.session.action.RegisterAction.run(RegisterAction.java:36) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:163) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.lambda$performActionAsync$2(PlayerSession.java:143) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

```

my config : 
mc server 1.14.4 Bukkit (LoginSecurity-3.0.1-Bukkit.jar)

database.yml
isolation: SERIALIZABLE
mysql:
  enabled: true
  host: 'localhost:3306'
  username: 'username'
  password: 'password'
  database: 'dbname'

**Comment by mqnoy** [comment]
#solved 

with : alter table ls_players add column uuid_mode varchar(1) check ( uuid_mode in ('M','U','O'));
