### ISSUE TITLE
Failed to deserialize item

### ISSUE THREAD

**Issue by mqnoy** [lenis0012/LoginSecurity-2#170]
```
java.io.EOFException: null
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2736) ~[?:1.8.0_242]
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3211) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readShort(ObjectInputStream.java:1044) ~[?:1.8.0_242]
	at java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:792) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:925) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1912) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1806) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2097) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1625) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2342) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2266) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2124) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1625) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2030) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1613) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:465) ~[?:1.8.0_242]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:423) ~[?:1.8.0_242]
	at com.lenis0012.bukkit.loginsecurity.util.InventorySerializer.deserialize(InventorySerializer.java:64) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.util.InventorySerializer.deserializeInventory(InventorySerializer.java:35) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.session.AuthAction.lambda$rehabPlayer$1(AuthAction.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:77) [server.jar:git-Bukkit-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:393) [server.jar:git-Bukkit-3e3818b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:971) [server.jar:git-Bukkit-3e3818b]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:380) [server.jar:git-Bukkit-3e3818b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:926) [server.jar:git-Bukkit-3e3818b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:780) [server.jar:git-Bukkit-3e3818b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[01:16:44] [Server thread/WARN]: [LoginSecurity] Task #140 for LoginSecurity v3.0.1 generated an exception
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_14_R1.inventory.CraftInventory.setContents(CraftInventory.java:84) ~[server.jar:git-Bukkit-3e3818b]
	at com.lenis0012.bukkit.loginsecurity.util.InventorySerializer.deserializeInventory(InventorySerializer.java:35) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.session.AuthAction.lambda$rehabPlayer$1(AuthAction.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:77) ~[server.jar:git-Bukkit-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:393) [server.jar:git-Bukkit-3e3818b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:971) [server.jar:git-Bukkit-3e3818b]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:380) [server.jar:git-Bukkit-3e3818b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:926) [server.jar:git-Bukkit-3e3818b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:780) [server.jar:git-Bukkit-3e3818b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

```

my server : 
Mc server Bukkit 1.14.4
LS version v3.0.1

**Comment by mqnoy** [comment]
I tried to clean the database and this problem is gone
