### ISSUE TITLE
Captcha problem

### ISSUE THREAD

**Issue by XenorInspire** [lenis0012/LoginSecurity-2#191]
Hi !
I download the project and I compiled it with Intellij (because i want to modify the plugin).
When I launch the plugin, i've this error : 

[18:21:00] [Server thread/ERROR]: Error occurred while enabling LoginSecurity v3.0.2 (Is it up to date?)
java.lang.NullPointerException: null
        at com.lenis0012.bukkit.loginsecurity.modules.general.GeneralModule.setupUpdater(GeneralModule.java:60) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.modules.general.GeneralModule.enable(GeneralModule.java:34) ~[?:?]
        at com.lenis0012.pluginutils.Registry.enableModule(Registry.java:88) ~[?:?]
        at com.lenis0012.pluginutils.Registry.enableModules(Registry.java:58) ~[?:?]
        at com.lenis0012.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot.jar:git-Spigot-800b93f-8160e29]
        at java.lang.Thread.run(Thread.java:830) [?:?]

How can I fix it ?
Thanks

**Comment by XenorInspire** [comment]
![Error](https://user-images.githubusercontent.com/44984461/84175098-c6236b80-aa7f-11ea-8579-0fa5cf61cb92.png)
