### ISSUE TITLE
error login security help

### ISSUE THREAD

**Issue by tommarekCZ** [lenis0012/LoginSecurity-2#198]
hello i need help from login security
it writes to me on the console
[INFO]: [LoginSecurity] Enabling LoginSecurity v2.0.10
[ERROR]: [LoginSecurity] Could not read from auth list!
someone will help

**Comment by tommarekCZ** [comment]
Please, write
to comment what should I do, thank you

**Comment by tommarekCZ** [comment]
Error occurred while enabling LoginSecurity v3.0.3-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'com.google.common.cache.LoadingCache com.google.common.cache.CacheBuilder.build(com.google.common.cache.CacheLoader)'
	at com.lenis0012.bukkit.loginsecurity.session.SessionManager.<init>(SessionManager.java:25) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.LoginSecurity.enable(LoginSecurity.java:89) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:27) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:352) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:326) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:282) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [bukkitserver.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]

**Comment by tommarekCZ** [comment]
help

**Comment by tommarekCZ** [comment]
solved
