### ISSUE TITLE
is clearing player inventory

### ISSUE THREAD

**Issue by Anyelo120** [lenis0012/LoginSecurity-2#210]
It started to crash after a reboot, how can I save the player's passwords and reinstall the plugin?

> [16:38:02 ERROR]: Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:536) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1698) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2054) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1635) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441) ~[?:1.8.0_262]
at com.lenis0012.bukkit.loginsecurity.util.InventorySerializer.deserialize(InventorySerializer.java:64) ~[?:?]
at com.lenis0012.bukkit.loginsecurity.util.InventorySerializer.deserializeInventory(InventorySerializer.java:35) ~[?:?]
at com.lenis0012.bukkit.loginsecurity.session.AuthAction.lambda$rehabPlayer$1(AuthAction.java:58) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [magma.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [magma.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
> [16:38:02 ERROR]: [LoginSecurity] Failed to deserialize item
java.io.IOException: Failed to deserialize object
at org.bukkit.util.io.BukkitObjectInputStream.newIOException(BukkitObjectInputStream.java:58) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:50) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1698) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2054) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1635) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483) ~[?:1.8.0_262]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441) ~[?:1.8.0_262]
at com.lenis0012.bukkit.loginsecurity.util.InventorySerializer.deserialize(InventorySerializer.java:64) ~[?:?]
at com.lenis0012.bukkit.loginsecurity.util.InventorySerializer.deserializeInventory(InventorySerializer.java:35) ~[?:?]
at com.lenis0012.bukkit.loginsecurity.session.AuthAction.lambda$rehabPlayer$1(AuthAction.java:58) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [magma.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [magma.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
> [16:38:02 WARN]: [LoginSecurity] Task #24058 for LoginSecurity v3.0.2 generated an exception
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setContents(CraftInventory.java:82) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at com.lenis0012.bukkit.loginsecurity.util.InventorySerializer.deserializeInventory(InventorySerializer.java:35) ~[?:?]
at com.lenis0012.bukkit.loginsecurity.session.AuthAction.lambda$rehabPlayer$1(AuthAction.java:58) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[magma.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [magma.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [magma.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by malpkakefirek** [comment]
I'm pretty sure you can copy the file `LoginSecurity.db` and after reinstalling the plugin, uploading it back to the folder
