### ISSUE TITLE
Problem with paper MC build 587

### ISSUE THREAD

**Issue by Alpha018** [lenis0012/LoginSecurity-2#233]
Hello, i have a problems with this plugin in a paper 1.16.5-587 and the console send me this error

![image](https://user-images.githubusercontent.com/24593811/114644572-c135d680-9ca5-11eb-9aef-4b1a75b49f33.png)
```
[21:45:47 ERROR]: Error occurred while disabling LoginSecurity v3.0.2 (Is it up to date?)
java.lang.NullPointerException: null
        at com.lenis0012.bukkit.loginsecurity.modules.storage.NewStorageModule.disable(NewStorageModule.java:58) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.disableModules(Registry.java:70) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onDisable(PluginHolder.java:33) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-591]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by EnderIce2** [comment]
For me, the dev release from [here](https://ci.codemc.io/job/lenis0012/job/LoginSecurity/) fixed my problem
