### ISSUE TITLE
Problem with mysql

### ISSUE THREAD

**Issue by foxodever** [lenis0012/LoginSecurity-2#241]
Hello. When i trying connect to mysql, plugin crashes.

**Comment by lenis0012** [comment]
Can you provide more information?

**Comment by APTKOP** [comment]
> Can you provide more information?

You replied for 1 fucking month, i already closed my server and forgot about this issue

**Comment by sebastiaannnn** [comment]
same issue here

**Comment by sebastiaannnn** [comment]
dm me on discord: Sebastiaan#7350
this thingy ain't gonna work otherwise

**Comment by Telesphoreo** [comment]
Same thing is happening here
```
[20:01:03 ERROR]: Error occurred while enabling LoginSecurity v3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/mysql/jdbc/jdbc2/optional/MysqlConnectionPoolDataSource
        at com.lenis0012.bukkit.loginsecurity.modules.storage.NewStorageModule.createMysqlDataSource(NewStorageModule.java:65) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.modules.storage.NewStorageModule.enable(NewStorageModule.java:39) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) ~[LoginSecurity-3.1-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-249]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-249]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-249]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 15 more
[20:01:03 INFO]: [LoginSecurity] Disabling LoginSecurity v3.1
[20:01:03 ERROR]: Error occurred while disabling LoginSecurity v3.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.lenis0012.bukkit.loginsecurity.database.datasource.SingleConnectionDataSource.shutdown()" because "this.dataSource" is null
        at com.lenis0012.bukkit.loginsecurity.modules.storage.NewStorageModule.disable(NewStorageModule.java:58) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.disableModules(Registry.java:70) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onDisable(PluginHolder.java:33) ~[LoginSecurity-3.1-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-249]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-249]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Telesphoreo** [comment]
Ok so I found the problem is that the dependencies are for 1.8.8 and are old. I patched the issue and you can get the updated JAR here https://github.com/Telesphoreo/LoginSecurity-2/releases/tag/3.1.1-SNAPSHOT

Just tested and it works

**Comment by trueyaya3** [comment]
seems like its not ok 
![image](https://user-images.githubusercontent.com/82025346/145656509-cbb64532-c9c7-4ad0-aeb1-22b84f20a27c.png)

**Comment by trueyaya3** [comment]
> Ok so I found the problem is that the dependencies are for 1.8.8 and are old. I patched the issue and you can get the updated JAR here https://github.com/Telesphoreo/LoginSecurity-2/releases/tag/3.1.1-SNAPSHOT
> 
> Just tested and it works

what deps and how did u patch them?

**Comment by sebastiaannnn** [comment]
hey, i lost you mind dming me again?
Sebastiaan#7350
