### ISSUE TITLE
MySql cannot be used

### ISSUE THREAD

**Issue by StealthDeci** [lenis0012/LoginSecurity-2#261]
**I am sure that there is nothing wrong with my ip and password**

[17:37:33 ERROR]: Error occurred while enabling LoginSecurity v3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/mysql/jdbc/jdbc2/optional/MysqlConnectionPoolDataSource
        at com.lenis0012.bukkit.loginsecurity.modules.storage.NewStorageModule.createMysqlDataSource(NewStorageModule.java:65) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.modules.storage.NewStorageModule.enable(NewStorageModule.java:39) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) ~[LoginSecurity-3.1-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Purpur-1330]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712) ~[patched_1.17.1.jar:git-Purpur-1330]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Purpur-1330]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1330]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1330]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Purpur-1330]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 15 more
[17:37:33 INFO]: [LoginSecurity] Disabling LoginSecurity v3.1
[17:37:33 ERROR]: Error occurred while disabling LoginSecurity v3.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.lenis0012.bukkit.loginsecurity.database.datasource.SingleConnectionDataSource.shutdown()" because "this.dataSource" is null
        at com.lenis0012.bukkit.loginsecurity.modules.storage.NewStorageModule.disable(NewStorageModule.java:58) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.disableModules(Registry.java:70) ~[LoginSecurity-3.1-Spigot.jar:?]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onDisable(PluginHolder.java:33) ~[LoginSecurity-3.1-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Purpur-1330]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Purpur-1330]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712) ~[patched_1.17.1.jar:git-Purpur-1330]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Purpur-1330]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1330]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1330]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by boyphongsakorn** [comment]
same error here

**Comment by sunxyw** [comment]
same error here. any fixes?
Paper 1.16.5, Java 16

**Comment by LemADEC** [comment]
Duplicate of #241

**Comment by lenis0012** [comment]
did you try using the latest version?

**Comment by lenis0012** [comment]
This should be fixed in the latest version, if not, please make a new issue.
