### ISSUE TITLE
 java.util.concurrent.ConcurrentHashMap cannot be cast to java.util.HashMap

### ISSUE THREAD

**Issue by games647** [lenis0012/LoginSecurity-2#27]
I get this Exception.

[23:18:19 ERROR]: Error occurred while enabling LoginSecurity v2.0.13 (Is it up to date?)
java.lang.ClassCastException: java.util.concurrent.ConcurrentHashMap cannot be cast to java.util.HashMap
        at com.lenis0012.bukkit.ls.LoginSecurity.loadAuthList(LoginSecurity.java:204) ~[?:?]
        at com.lenis0012.bukkit.ls.LoginSecurity.onEnable(LoginSecurity.java:158) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-b1c1b5

**Comment by lenis0012** [comment]
Try with 2.0.14-SNAPSHOT from [Jenkins](http://ci.lenis0012.com/job/LoginSecurity/)

**Comment by games647** [comment]
It works. Thank you.
