### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Vilican** [lenis0012/LoginSecurity-2#33]
There is a bug when I try to use MySQL database:

```
[12:23:58] [Server thread/INFO]: MYSQL
[12:23:58] [Server thread/INFO]: [LoginSecurity] Connection to database....
[12:23:58] [Server thread/INFO]: DataSourcePool [LoginSecurityDB] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[12:23:59] [Server thread/INFO]: DatabasePlatform name:LoginSecurityDB platform:mysql
[12:23:59] [Server thread/INFO]: SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
[12:23:59] [Server thread/INFO]: Entities enhanced[0] subclassed[5]
[12:23:59] [Server thread/INFO]: [LoginSecurity] Checking database version...
[12:23:59] [Server thread/INFO]: [LoginSecurity] Applying database upgrade 1: Initial
[12:23:59] [Server thread/INFO]: runScript
[12:23:59] [Server thread/INFO]: executing 1 of 7 create table ls_actions ( id                            integer auto_increment n...
[12:23:59] [Server thread/INFO]: executing 2 of 7 create table ls_upgrades ( id                            integer auto_increment...
[12:23:59] [Server thread/INFO]: executing 3 of 7 create table ls_inventories ( id                            integer auto_increme...
[12:23:59] [Server thread/INFO]: executing 4 of 7 create table ls_locations ( id                            integer auto_increment...
[12:23:59] [Server thread/INFO]: executing 5 of 7 create table ls_players ( id                            integer auto_increment n...
[12:23:59] [Server thread/INFO]: executing 6 of 7 alter table ls_players add constraint fk_ls_players_location_id foreign key (loc...
[12:23:59] [Server thread/INFO]: executing 7 of 7 alter table ls_players add constraint fk_ls_players_inventory_id foreign key (in...
[12:23:59] [Server thread/INFO]: ... end of script
[12:23:59] [Server thread/INFO]: [LoginSecurity] Applying database upgrade 2: Add uuid mode
[12:23:59] [Server thread/INFO]: runScript
[12:23:59] [Server thread/INFO]: executing 1 of 1 alter table ls_players add column uuid_mode varchar(1) check ( uuid_mode in ('M'...
[12:23:59] [Server thread/INFO]: ... end of script
[12:23:59] [Server thread/INFO]: [LoginSecurity] Applied 2 missing database upgrades.
[12:23:59] [Server thread/WARN]: [LoginSecurity] Couldn't check mysql database
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mc_login.users' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504) ~[patched_1.10.jar:git-Paper-788]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370) ~[patched_1.10.jar:git-Paper-788]
	at com.lenis0012.bukkit.loginsecurity.modules.migration.LegacyMigration.executeAutomatically(LegacyMigration.java:37) [LoginSecurity-Spigot-2.1-BETA02-SNAPSHOT.jar:?]
	at com.lenis0012.bukkit.loginsecurity.modules.migration.MigrationModule.enable(MigrationModule.java:32) [LoginSecurity-Spigot-2.1-BETA02-SNAPSHOT.jar:?]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) [LoginSecurity-Spigot-2.1-BETA02-SNAPSHOT.jar:?]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) [LoginSecurity-Spigot-2.1-BETA02-SNAPSHOT.jar:?]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) [LoginSecurity-Spigot-2.1-BETA02-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [patched_1.10.jar:git-Paper-788]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.jar:git-Paper-788]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.jar:git-Paper-788]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.jar:git-Paper-788]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.jar:git-Paper-788]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.jar:git-Paper-788]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.jar:git-Paper-788]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.jar:git-Paper-788]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.jar:git-Paper-788]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.jar:git-Paper-788]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[12:23:59] [Server thread/INFO]: [LoginSecurity] Registering commands...
[12:23:59] [Server thread/INFO]: [LoginSecurity] Registering listeners...
```

My database config:

```
isolation: SERIALIZABLE
mysql:
  enabled: true
  host: '192.168.2.45:3306'
  username: 'mc_login'
  password: 'MySecretPass'
  database: 'mc_login'
```

This bug appears on all LS 2.1 versions.

**Comment by lenis0012** [comment]
I will resolve it asap :)
It should not ecause any ingame problems tho

**Comment by Vilican** [comment]
Oops! Still a bug:

`[20:12:33] [Server thread/INFO]: [LoginSecurity] Enabling LoginSecurity v2.1.1
[20:12:33] [Server thread/INFO]: MYSQL
[20:12:33] [Server thread/INFO]: [LoginSecurity] Connection to database....
[20:12:33] [Server thread/INFO]: DataSourcePool [LoginSecurityDB] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[20:12:34] [Server thread/INFO]: DatabasePlatform name:LoginSecurityDB platform:mysql
[20:12:34] [Server thread/INFO]: SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
[20:12:34] [Server thread/INFO]: Entities enhanced[0] subclassed[5]
[20:12:34] [Server thread/INFO]: [LoginSecurity] Checking database version...
[20:12:34] [Server thread/INFO]: [LoginSecurity] Applied 0 missing database upgrades.
[20:12:34] [Server thread/WARN]: [LoginSecurity] Couldn't check mysql database
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mc_login.users' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504) ~[patched_1.10.jar:git-Paper-792]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370) ~[patched_1.10.jar:git-Paper-792]
	at com.lenis0012.bukkit.loginsecurity.modules.migration.LegacyMigration.executeAutomatically(LegacyMigration.java:37) [LoginSecurity-Spigot-2.1.1.jar:git-LoginSecurity-aa4ca3f]
	at com.lenis0012.bukkit.loginsecurity.modules.migration.MigrationModule.enable(MigrationModule.java:32) [LoginSecurity-Spigot-2.1.1.jar:git-LoginSecurity-aa4ca3f]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) [LoginSecurity-Spigot-2.1.1.jar:git-LoginSecurity-aa4ca3f]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) [LoginSecurity-Spigot-2.1.1.jar:git-LoginSecurity-aa4ca3f]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) [LoginSecurity-Spigot-2.1.1.jar:git-LoginSecurity-aa4ca3f]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [patched_1.10.jar:git-Paper-792]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.jar:git-Paper-792]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.jar:git-Paper-792]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.jar:git-Paper-792]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.jar:git-Paper-792]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[20:12:34] [Server thread/INFO]: [LoginSecurity] Registering commands...
[20:12:34] [Server thread/INFO]: [LoginSecurity] Registering listeners...`

**Comment by lenis0012** [comment]
@Vilican It is checking to see if the old database exists so i will migrate.
However, it already has, thats why its giving this error.

Its not a problem and i just need to make it ignore that specific error, means theres no old data left to migrate

**Comment by lenis0012** [comment]
Will be fixe din 2.1.2+
