### ISSUE TITLE
Register Again!

### ISSUE THREAD

**Issue by PinoyLifeCraft** [lenis0012/LoginSecurity-2#35]
I'm using the later Version of LoginSecurity Build 89 for 1.9 and 1.10

After i update '/lac update' and Reboot the Server I get Spam Message 
'Please Register using /register <password>' and if i Register i get error!

[17:34:16] [pool-5-thread-1/WARN]: Exception in thread "pool-5-thread-1" 
[17:34:16] [pool-5-thread-1/WARN]: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[assertion failure: param count (11) != value count (22)]
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.lenis0012.bukkit.loginsecurity.session.action.RegisterAction.run(RegisterAction.java:34)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:158)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:132)
[17:34:17] [pool-5-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:34:17] [pool-5-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:34:17] [pool-5-thread-1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[17:34:17] [pool-5-thread-1/WARN]: Caused by: java.sql.SQLException: assertion failure: param count (11) != value count (22)
[17:34:17] [pool-5-thread-1/WARN]: 	at org.sqlite.DB.execute(DB.java:320)
[17:34:17] [pool-5-thread-1/WARN]: 	at org.sqlite.DB.executeUpdate(DB.java:363)
[17:34:17] [pool-5-thread-1/WARN]: 	at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:74)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:158)
[17:34:17] [pool-5-thread-1/WARN]: 	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105)
[17:34:17] [pool-5-thread-1/WARN]: 	... 17 more

[latest.zip](https://github.com/lenis0012/LoginSecurity-2/files/322186/latest.zip)

**Comment by lenis0012** [comment]
From what version did you upgrade?
Also, what command did you type?
/register xxxxxx?

**Comment by lenis0012** [comment]
Duplicate of #40 
Fixed in latest version (hopefully)

Thanks for submitting
