### ISSUE TITLE
Users can't login 

### ISSUE THREAD

**Issue by exos** [lenis0012/LoginSecurity-2#39]
When a user try to login, it seems that is success. The blink effect disappear but the player can't moved out of spawn area and the message of "Please log in using /login" continues showing.

In the logs of server:
```
jun 25 01:18:18 servercraft start_server.sh[5183]: [01:18:18 INFO]: exos[/x.x.x.x:55050] logged in with entity id 1664 at ([world]-405.0, 46.0, 248.0)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]: Exception in thread "pool-4-thread-3"
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]: java.lang.IllegalArgumentException: Name cannot be null
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at org.apache.commons.lang.Validate.notNull(Validate.java:192)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at org.bukkit.craftbukkit.v1_9_R2.CraftServer.getWorld(CraftServer.java:977)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at org.bukkit.Bukkit.getWorld(Bukkit.java:509)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at com.lenis0012.bukkit.loginsecurity.storage.PlayerLocation.asLocation(PlayerLocation.java:46)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at com.lenis0012.bukkit.loginsecurity.session.AuthAction.rehabPlayer(AuthAction.java:65)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at com.lenis0012.bukkit.loginsecurity.session.action.LoginAction.run(LoginAction.java:23)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:159)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:133)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jun 25 01:18:25 servercraft start_server.sh[5183]: [01:18:25 WARN]:         at java.lang.Thread.run(Unknown Source)
jun 25 01:18:35 servercraft start_server.sh[5183]: [01:18:35 INFO]: exos lost connection: Disconnected
jun 25 01:18:35 servercraft start_server.sh[5183]: [01:18:35 INFO]: exos left the game.
```

I'm ussing CraftBukkit Minecraft server, version "git-Bukkit-0cd0397"

**Comment by lenis0012** [comment]
Can you try with the latest dev build?
http://ci.lenis0012.com/job/LoginSecurity

**Comment by lenis0012** [comment]
Also, this is a duplicate of the resolved issue #38

**Comment by lenis0012** [comment]
@exos ci.lenis0012.com/job/LoginSecurity

**Comment by exos** [comment]
Thank you, now its works!
