### ISSUE TITLE
MySQL exception

### ISSUE THREAD

**Issue by Vilican** [lenis0012/LoginSecurity-2#40]
First - everything works. However, in console appear this message:

```
11:44:25 [WARN] Exception in thread "pool-6-thread-1"
11:44:25 [WARN] javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[Duplicate entry '19' for key 'PRIMARY']
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveAssocOne(DefaultPersister.java:1229)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:432)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619)
11:44:25 [WARN] 	at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$1.run(PlayerSession.java:48)
11:44:25 [WARN] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
11:44:25 [WARN] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
11:44:25 [WARN] 	at java.lang.Thread.run(Thread.java:745)
11:44:25 [WARN] Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '19' for key 'PRIMARY'
11:44:25 [WARN] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
11:44:25 [WARN] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
11:44:25 [WARN] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
11:44:25 [WARN] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
11:44:25 [WARN] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
11:44:25 [WARN] 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
11:44:25 [WARN] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
11:44:25 [WARN] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
11:44:25 [WARN] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
11:44:25 [WARN] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
11:44:25 [WARN] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
11:44:25 [WARN] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
11:44:25 [WARN] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
11:44:25 [WARN] 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
11:44:25 [WARN] 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
11:44:25 [WARN] 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
11:44:25 [WARN] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:74)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:158)
11:44:25 [WARN] 	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105)
11:44:25 [WARN] 	... 19 more
```

**Comment by lenis0012** [comment]
full log?
pastebin please

**Comment by Vilican** [comment]
http://pastebin.com/eFTpDJsE

**Comment by lenis0012** [comment]
okay.
Is this an issue that only occurs right after restart?

**Comment by Vilican** [comment]
No, when user connects.

**Comment by lenis0012** [comment]
@Vilican Could it be multiple users were trying to connect at once?

**Comment by lenis0012** [comment]
@Vilican I dont know how to reproduce this issue :/
I ran LoginSecurity on 1.10 offline-mode with 2 test accounts and everything works fine.

Can you give me your settings + database-settings?

**Comment by Vilican** [comment]
No, this issue appears when even a single user tries to log in.

**Comment by Vilican** [comment]
Database (hashes of course removed): https://sufix.cz/res/files/mc_login.sql

**Comment by Vilican** [comment]
Version: build #103

**Comment by Vilican** [comment]
Conf: https://sufix.cz/res/files/LoginSecurity.zip

**Comment by lenis0012** [comment]
@Vilican Does it work when you turn location: SPAWN off?
Im pretty sure its a conflict that occurs when both location and hide-inventory are enabled.

I will test to verify and fix asap :)
