### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CraftYourWay** [lenis0012/LoginSecurity-2#48]
spigot 1.10.2 error log:

[16:45:49] [Server thread/ERROR]: Could not pass event FoodLevelChangeEvent to LoginSecurity v2.1.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:661) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MobEffectList.tick(MobEffectList.java:75) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MobEffect.b(SourceFile:111) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MobEffect.tick(SourceFile:98) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.EntityLiving.tickPotionEffects(EntityLiving.java:532) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.citizensnpcs.npc.entity.EntityHumanNPC.m(EntityHumanNPC.java:283) [Citizens.jar:?]
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:51) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:728) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Can't retrieve player session from offline player!
	at com.lenis0012.bukkit.loginsecurity.session.SessionManager.getPlayerSession(SessionManager.java:41) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onFoodLevelChange(PlayerListener.java:256) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[lobby.jar:git-Spigot-a9631d2-67b2424]
	... 19 more

**Comment by lenis0012** [comment]
Did you ever reload the server?

**Comment by CraftYourWay** [comment]
nop i never reloaded the server even tried the latest 2.1.4 version but still an error:

Could not pass event FoodLevelChangeEvent to LoginSecurity v2.1.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:661) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MobEffectList.tick(MobEffectList.java:75) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MobEffect.b(SourceFile:111) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MobEffect.tick(SourceFile:98) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.EntityLiving.tickPotionEffects(EntityLiving.java:532) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.citizensnpcs.npc.entity.EntityHumanNPC.m(EntityHumanNPC.java:283) [Citizens.jar:?]
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:51) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:728) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [lobby.jar:git-Spigot-a9631d2-67b2424]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Can't retrieve player session from offline player!
	at com.lenis0012.bukkit.loginsecurity.session.SessionManager.getPlayerSession(SessionManager.java:41) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onFoodLevelChange(PlayerListener.java:256) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[lobby.jar:git-Spigot-a9631d2-67b2424]
	... 19 more

i did not reload i did not do anything an offline player comes online and i get the error but its not just 1 time it spams the whole server and after a while it crashes the server

**Comment by Tzzzt123** [comment]
restart the server lol

**Comment by CraftYourWay** [comment]
wow, you really think ill restart my server 100 times a day, then u got it wrong.

**Comment by lenis0012** [comment]
@CraftYourWay I will look into it.
It seems like it woould be an issue with reload or a plugin manager;

but i will verify and resolve if possible

**Comment by lenis0012** [comment]
do you use a plugin like Citizens or any other human-interacting plugin
maybe an anticheat with anti-forcefield.

**Comment by Tzzzt123** [comment]
or you can upgrade/downgrade loginsecurity
(last dev version: 2.1.4)

**Comment by CraftYourWay** [comment]
yes i do use citizens but when i did not used it in my old authlobby it did the same

**Comment by Tzzzt123** [comment]
then backup loginsecurity files and delete loginsecurity and reput the files
and then add loginsecurity again
