### ISSUE TITLE
errr

### ISSUE THREAD

**Issue by dyanakiev** [lenis0012/LoginSecurity-2#50]
```
[01:20:10 ERROR]: Could not pass event EntityDamageByEntityEvent to LoginSecurity v2.1.3
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-813]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:867) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:792) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:515) [patched_1.10.2.jar:git-Paper-813]
        at net.citizensnpcs.npc.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:121) [citizens-2.0.19-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1029) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1171) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1616) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:48) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:5) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-813]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:796) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.2.jar:git-Paper-813]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Can't retrieve player session from offline player!
        at com.lenis0012.bukkit.loginsecurity.session.SessionManager.getPlayerSession(SessionManager.java:41) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onEntityDamage(PlayerListener.java:266) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-813]
        ... 28 more
```

**Comment by dyanakiev** [comment]
```
>lac
[12:54:58 INFO]: LoginSecurity Admin Command:
[12:54:58 INFO]: /rmpass<username> - Remove a user's password
[12:54:58 INFO]: /dbimport<source> [args] - Import from another database
[12:54:58 INFO]: An error occured while executing this command, please contact an admin!
[12:54:58 ERROR]: Error while running command
java.lang.NullPointerException
        at com.lenis0012.bukkit.loginsecurity.modules.language.TranslatedMessage.param(TranslatedMessage.java:12) ~[LoginSecurity-2.1.3-Spigot.jar:git-LoginSecurity-cd160c0]
        at com.lenis0012.bukkit.loginsecurity.commands.CommandAdmin.execute(CommandAdmin.java:63) ~[LoginSecurity-2.1.3-Spigot.jar:git-LoginSecurity-cd160c0]
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.modules.command.Command.onCommand(Command.java:50) [LoginSecurity-2.1.3-Spigot.jar:git-LoginSecurity-cd160c0]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) [patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) [patched_1.10.2.jar:git-Paper-813]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:628) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:441) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.2.jar:git-Paper-813]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.2.jar:git-Paper-813]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

```

**Comment by lenis0012** [comment]
did you update to the latest version?

**Comment by lenis0012** [comment]
due to lack of response im goign to assume this issue has been resolved.
Please make a new ticket with a better title if it still occurs
