### ISSUE TITLE
/lac rmpass still doesn't work

### ISSUE THREAD

**Issue by Tzzzt123** [lenis0012/LoginSecurity-2#52]
Console LOG:
[11:23:41 INFO]: No player with that name has been registered! [11:23:41 WARN]: Exception in thread "pool-6-thread-1" [11:23:41 WARN]: java.lang.IllegalStateException: User is not registered! 
[11:23:41 WARN]:        at com.lenis0012.bukkit.loginsecurity.session.action.RemovePassAction.run(RemovePassAction.java:15) [11:23:41 WARN]:        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:168) [11:23:41 WARN]:        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:142) [11:23:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 [11:23:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
[11:23:41 WARN]:        at java.lang.Thread.run(Thread.java:745)

Server version: Spigot 1.9.4

**Comment by Tzzzt123** [comment]
please answer @lenis0012

**Comment by Plazmaz** [comment]
@Tzzzt123 Please be patient. It's currently 7:22 AM here and everyone's still waking up.

**Comment by Tzzzt123** [comment]
@Plazmaz i just watched @lenis0012 location: "NETHERLANDS"
And in there time zone CEST so 15:25

**Comment by Plazmaz** [comment]
@Tzzzt123 he is currently on vacation in the USA.. Please calm down.

**Comment by Tzzzt123** [comment]
oh sorry @lenis0012

**Comment by lenis0012** [comment]
@Tzzzt123 Try the latest dev build.
Also make sure the name is correct. it is case sensitive
