### ISSUE TITLE
Could not pass event FoodLevelChangeEvent to LoginSecurity error

### ISSUE THREAD

**Issue by Vilican** [lenis0012/LoginSecurity-2#60]
I got this error in my console. No idea what it means, but can you fix it?

```
15:23:35 [WARN] HexxitLP was kicked for floating too long!
15:23:35 [INFO] HexxitLP lost connection: Flying is not enabled on this server
15:23:36 [INFO] HexxitLP left the game
15:23:36 [ERROR] Could not pass event FoodLevelChangeEvent to LoginSecurity v2.1.4
15:23:36 org.bukkit.event.EventException
15:23:36 at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-824]
15:23:36 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-824]
15:23:36 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-824]
15:23:36 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:661) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.MobEffectList.tick(MobEffectList.java:75) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.MobEffect.b(SourceFile:111) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.MobEffect.tick(SourceFile:98) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.EntityLiving.tickPotionEffects(EntityLiving.java:538) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:286) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.Entity.m(Entity.java:321) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:156) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:257) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:152) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:886) [patched_1.10.2.jar:git-Paper-824]
15:23:36 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
15:23:37 Caused by: java.lang.IllegalStateException: Can't retrieve player session from offline player!
15:23:37 at com.lenis0012.bukkit.loginsecurity.session.SessionManager.getPlayerSession(SessionManager.java:42) ~[?:?]
15:23:37 at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onFoodLevelChange(PlayerListener.java:271) ~[?:?]
15:23:37 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor128.execute(Unknown Source) ~[?:?]
15:23:37 at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-824]
15:23:37 ... 22 more
15:23:37 [WARN] HexxitLP was kicked for floating too long!
15:23:37 [ERROR] Could not pass event FoodLevelChangeEvent to LoginSecurity v2.1.4
15:23:37 org.bukkit.event.EventException
15:23:37 at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-824]
15:23:37 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-824]
15:23:37 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-824]
15:23:37 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:661) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MobEffectList.tick(MobEffectList.java:75) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MobEffect.b(SourceFile:111) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MobEffect.tick(SourceFile:98) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityLiving.tickPotionEffects(EntityLiving.java:538) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:286) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.Entity.m(Entity.java:321) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:156) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:257) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:152) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:886) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
15:23:37 Caused by: java.lang.IllegalStateException: Can't retrieve player session from offline player!
15:23:37 at com.lenis0012.bukkit.loginsecurity.session.SessionManager.getPlayerSession(SessionManager.java:42) ~[?:?]
15:23:37 at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onFoodLevelChange(PlayerListener.java:271) ~[?:?]
15:23:37 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor128.execute(Unknown Source) ~[?:?]
15:23:37 at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-824]
15:23:37 ... 22 more
15:23:37 [WARN] HexxitLP was kicked for floating too long!
15:23:37 [ERROR] Could not pass event FoodLevelChangeEvent to LoginSecurity v2.1.4
15:23:37 org.bukkit.event.EventException
15:23:37 at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-824]
15:23:37 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-824]
15:23:37 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-824]
15:23:37 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:661) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MobEffectList.tick(MobEffectList.java:75) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MobEffect.b(SourceFile:111) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.MobEffect.tick(SourceFile:98) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityLiving.tickPotionEffects(EntityLiving.java:538) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:286) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.Entity.m(Entity.java:321) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:156) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:257) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139) [patched_1.10.2.jar:git-Paper-824]
15:23:37 at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [patched_1.10.2.jar:git-Paper-824]
15:23:38 at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:152) [patched_1.10.2.jar:git-Paper-824]
15:23:38 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:886) [patched_1.10.2.jar:git-Paper-824]
15:23:38 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-824]
15:23:38 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-824]
15:23:38 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-824]
15:23:38 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
15:23:38 Caused by: java.lang.IllegalStateException: Can't retrieve player session from offline player!
15:23:38 at com.lenis0012.bukkit.loginsecurity.session.SessionManager.getPlayerSession(SessionManager.java:42) ~[?:?]
15:23:38 at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onFoodLevelChange(PlayerListener.java:271) ~[?:?]
15:23:38 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor128.execute(Unknown Source) ~[?:?]
15:23:38 at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-824]
15:23:38 ... 22 more
```

**Comment by lenis0012** [comment]
Yes will do

**Comment by lenis0012** [comment]
@Vilican still happening?

**Comment by Vilican** [comment]
Oh, sorry. Not in the latest version, I think.
