### ISSUE TITLE
Error when many players join

### ISSUE THREAD

**Issue by TrademarkTM** [lenis0012/LoginSecurity-2#64]
Hey!
I'm currently having this error in console:

>13.08 09:59:15 [Server] ERROR Could not pass event PlayerJoinEvent to LoginSecurity v2.1.4
13.08 09:59:15 [Server] INFO org.bukkit.event.EventException
13.08 09:59:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
13.08 09:59:15 [Server] INFO Caused by: java.lang.IllegalStateException: Can't save profile when not registered!
13.08 09:59:15 [Server] INFO at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.saveProfileAsync(PlayerSession.java:43) ~[?:?]
13.08 09:59:15 [Server] INFO at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onPlayerJoin(PlayerListener.java:108) ~[?:?]
13.08 09:59:15 [Server] INFO at sun.reflect.GeneratedMethodAccessor285.invoke(Unknown Source) ~[?:?]
13.08 09:59:15 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
13.08 09:59:15 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
13.08 09:59:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot%201.8.8.jar:git-Spigot-db6de12-18fbb24]
13.08 09:59:15 [Server] INFO ... 14 more

**Comment by gianmorita** [comment]
I'm getting the same error here:

`[10:20:23] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to LoginSecurity v2.1.4
org.bukkit.event.EventException
	at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:77) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-5e5cf84]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:317) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:144) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:115) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:53) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:224) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.ServerConnection.c(SourceFile:187) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:758) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Can't save profile when not registered!
	at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.saveProfileAsync(PlayerSession.java:43) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onPlayerJoin(PlayerListener.java:108) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:67) ~[?:?]
	... 14 more`

**Comment by lenis0012** [comment]
is your password-requires settting set to true?

**Comment by TrademarkTM** [comment]
Yes, it is.

**Comment by lenis0012** [comment]
What version of spiogt & loginsecurity are you running?
/version
/version LoginSecurity

**Comment by lenis0012** [comment]
Should be fixed in 2.1.5
