### ISSUE TITLE
Failed to migrate database

### ISSUE THREAD

**Issue by leetom** [lenis0012/LoginSecurity-2#66]
I got this error when use LoginSecurity, with MySQL 5.6

```
    [17:16:47 ERROR]: [LoginSecurity] Failed to migrate database
    java.sql.SQLException: Column 'ip' not found.
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1144) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at com.lenis0012.bukkit.loginsecurity.modules.migration.LegacyMigration.getProfile(LegacyMigration.java:162) ~[LoginSecurity.jar:git-LoginSecurity-cf1b468]
            at com.lenis0012.bukkit.loginsecurity.modules.migration.AbstractMigration.loadProfiles(AbstractMigration.java:116) ~[LoginSecurity.jar:git-LoginSecurity-cf1b468]
            at com.lenis0012.bukkit.loginsecurity.modules.migration.LegacyMigration.execute(LegacyMigration.java:80) [LoginSecurity.jar:git-LoginSecurity-cf1b468]
            at com.lenis0012.bukkit.loginsecurity.modules.migration.MigrationModule.enable(MigrationModule.java:33) [LoginSecurity.jar:git-LoginSecurity-cf1b468]
            at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) [LoginSecurity.jar:git-LoginSecurity-cf1b468]
            at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) [LoginSecurity.jar:git-LoginSecurity-cf1b468]
            at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) [LoginSecurity.jar:git-LoginSecurity-cf1b468]
            at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
            at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
```

Also there would be an error that the index `uq_ls_upgrades_version`  is too long if the default charset is utf8mb4.

**Comment by lenis0012** [comment]
did this happen while updating LoginSecurity?
or with a new install

**Comment by leetom** [comment]
@lenis0012  on a new install, and I choose to use MySQL. The MC server is spigot 1.8.8 (_spigot-1.8.8-R0.1-SNAPSHOT-latest.jar_)

**Comment by lenis0012** [comment]
@leetom the fact that it tries to migrate indicate that an old database already exists.
OR, there is a table called "users" in your mysql database, which LoginSecurity assumes is a LoginSecurity 1.X user database.

If thats the case, can you put LoginSecurity in its own database and see if it works?
