### ISSUE TITLE
NullPointerException | 1.8.8

### ISSUE THREAD

**Issue by TrademarkTM** [lenis0012/LoginSecurity-2#70]
I had this error today in my console:
I've no ideia what caused it.

``
[16:21:54 WARN]: [LoginSecurity] Task #163 for LoginSecurity v2.1.6 generated an exception
java.lang.NullPointerException
        at com.lenis0012.bukkit.loginsecurity.modules.general.GeneralModule$3$1.run(GeneralModule.java:140) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot%201.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
``

Also, there's a small bug. When you use /logout, the plugin kicks you for taking too long to login (instantly). So it doesn't reset/stays counting the time even after login.

I've tested the /lac rmpass, and when you removes the password of a player and he keeps online, the map doesn't update and you get kicked for wrong captcha.

The map does not get removed from your inventory if you use /register and do not type the password.

Another two errors I found right now (/lac rmpass bug):
http://hastebin.com/abutobuqub.md

**Now some ideas**
- [ ] Like the another thread, /register [password] [confirm password] would be really useful.
- [ ] The map captcha is great, but sometimes if the player spawns in a block - e.g. I reset his password and he logs in again - it's impossible to see the map, so no way to complete it. Maybe teleport him to somewhere or make sure he is not glitching?
- [ ] /unregister command? I know there's /lac rmpass, but only for admins.

**Comment by Plazmaz** [comment]
Seems to be caused by version.getType().toString()

**Comment by lenis0012** [comment]
These are quite a few issues/suggestions.

ill see when i have time

**Comment by lenis0012** [comment]
Fixed the issue, it's in the latest dev build.
As for the feature requests.

Like the another thread, /register [password] [confirm password] would be really useful.
Please see #67 

I will make a separate issue for the other 2 requests.
