### ISSUE TITLE
Don't allow player's to log on with a differently-cased username in offline mode

### ISSUE THREAD

**Issue by swordin** [lenis0012/LoginSecurity-2#85]
Hello,

I use your cool plugin LoginSecurity v.2.1.6 under Paper version git-Paper-819 (MC: 1.10.2).

I found a serious problem: your plugin considers uppercase and lowercase letters in the name of a player as the _different players_. While the other plugins consider ‘ABCdef’ player and ‘abcDEF’ player — as the _same player_. 

Look. In my case there is **BeneJe** player (with status 'premium'). But the hacker comes under the name **Beneje**. This plugin rewrites player's file (look below), and changes his status (Beneje becomes default player instead of premium as he was). Additionally, when I try to kick or ban - both players are banned. 

If both players are online, then I got the error: **NoCheatPlus mistaken** in counting (look below), and **your plugin displays an error message**. 

Please correct! A large letter or a small - the plugin must consider it as the same player!

Thank you for your reply!

[20:16:36 INFO]: [Essentials] Found new UUID for Benejo. Replacing 94580db7-19c6-32ed-a2da-55f13b132ea4 with 689bff8e-9ffa-3102-ac7f-8fd1ce8ba55c
[20:16:37 INFO]: [Player] Benejo enters.

[20:18:10 INFO]: [Essentials] Found new UUID for BeneJo. Replacing 689bff8e-9ffa-3102-ac7f-8fd1ce8ba55c with 94580db7-19c6-32ed-a2da-55f13b132ea4
[20:18:11 INFO]: [Premier] BeneJo enters.

>
>who
[20:19:28 INFO]: CONSOLE issued server command: /who 
[20:19:28 INFO]: Now 5 of 120 players.
[20:19:28 INFO]: default: [Player] Benejo, [Player] Life4five
[20:19:28 INFO]: premium: [Premier] aluvia, [Premier] BeneJo
[20:19:28 INFO]: vip: [VIP] 1929384756

[20:20:40 WARN]: [LoginSecurity] Task #9 for LoginSecurity v2.1.6 generated an exception
java.lang.NullPointerException
        at com.lenis0012.bukkit.loginsecurity.modules.threading.TimeoutTask.run(TimeoutTask.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [PaperSpigot.jar:git-Paper-819]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[20:20:41 WARN]: [LoginSecurity] Task #9 for LoginSecurity v2.1.6 generated an exception
java.lang.NullPointerException
        at com.lenis0012.bukkit.loginsecurity.modules.threading.TimeoutTask.run(TimeoutTask.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [PaperSpigot.jar:git-Paper-819]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

[20:20:43 WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (4 instead of 5)
[20:20:53 WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (4 instead of 5)
[20:21:03 WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (4 instead of 5)

Regards, 
Alexander Swordin, 
swordin@me.com.

**Comment by lenis0012** [comment]
That's right.
LoginSecurity does not assume that servers let both offline-mode and online-mode players on.
Are you using a plugin that does this?

**Comment by lenis0012** [comment]
If you use FastLogin, could you try enabling autoRegister in the config?

**Comment by swordin** [comment]
>> That's right.
>> LoginSecurity does not assume that servers let both offline-mode and online-mode players on.
>> Are you using a plugin that does this?

no, my server let offline-mode only
if I understand you right



> If you use FastLogin, could you try enabling autoRegister in the config?

Hm… I use LoginSecurity (for users authentication) only. It’s just about LoginSecurity.
Should I provide all the plugin list for you?

**Comment by swordin** [comment]
screenshot illustrated that LoginSecurity considers «BeneJo» and «Benejo» as the different players: 

root@swordinmec-vps-2:~/LightServer/plugins/Essentials/userdata# grep -i -r "Bene"
689bff8e-9ffa-3102-ac7f-8fd1ce8ba55c.yml:lastAccountName: Benejo
94580db7-19c6-32ed-a2da-55f13b132ea4.yml:lastAccountName: BeneJo

**Comment by lenis0012** [comment]
Looking further into this.
You'll hear from me as soon as i know whats going on

**Comment by Tzzzt123** [comment]
@swordin @lenis0012 Offline-Mode servers also let "Paid"/"Premium" minecraft accounts come online
Just to say...

**Comment by swordin** [comment]
no! this is another case. no "paid"/"premium" accounts here. just the same player under two similar nics.

**Comment by Tzzzt123** [comment]
ok

**Comment by swordin** [comment]
>  You'll hear from me as soon as i know whats going on

So when will we hear from you? We're waiting for update to 2.0. The bugs occur since 2016. Please update the plugin!

**Comment by swordin** [comment]
So when the plugin will be renew??? 

Thousands of your clients become hostages (((

**Comment by lenis0012** [comment]
Offline mode should be detected based on matching the player's UUID with OfflinePlayer:PlayerName.
