### ISSUE TITLE
LoginSecurity: /rmpass causes Java error

### ISSUE THREAD

**Issue by swordin** [lenis0012/LoginSecurity-2#87]
Hello, 

As I can see - the next features do not work properly (or do not exist):
- user can't change the password
- admin can't reset the user's password
- admin can't delete the registered user (totally from server)

Thank you.

**Comment by Tzzzt123** [comment]
Please tell me your server's version and your version of LoginSecurity. That would be very helpful for fixing your problem. Thanks Tzzzt123

**Comment by swordin** [comment]
minecraft.server.v1_10_R1
PaperSpigot.jar:git-Paper-819
LoginSecurity - the last available (in dev.bukkit.org) version - 2.1.6

**Comment by Tzzzt123** [comment]
ok. Try to use Spigot "official" build and tell me if it still bugs.

**Comment by swordin** [comment]
excuse me, where could I download it?

**Comment by Tzzzt123** [comment]
you have to build it: get [Buildtools](https://hub.spigotmc.org/jenkins/job/BuildTools/) and [Git](https://git-for-windows.github.io/) then you make a start.sh file:
Insert this in this file: "java -jar BuildTools.jar --rev <minecraftversion>" (without "")(<minecraftversion>=version of minecraft (Ex. 1.9.4)
right click the start.sh file and it starts to build.
Click [here](https://www.spigotmc.org/wiki/buildtools/) for further information

**Comment by swordin** [comment]
mm... it is quite difficult for me, sorry ((
there's a saying: "do not touch while it's running good"

I'd rather wait a new version of LoginSecurity

thank you for you help

**Comment by swordin** [comment]
all right

so, the main questions: 

- how can admin change or reset the user's password
- how can admin delete the registered user (totally from server)
..?

thank you

**Comment by Tzzzt123** [comment]
reset a users password command is /lac rmpass

**Comment by swordin** [comment]
I can see in description: 

"...temporary removed in 2.1..."
( https://dev.bukkit.org/projects/loginsecurity?gameCategorySlug=bukkit-plugins&projectID=41702 )

**Comment by swordin** [comment]
...and it causes java-errors

**Comment by Tzzzt123** [comment]
The /rmpass command is removed in 2.1 (/rmpass is to be issued by the player) and /lac rmpass should work
@swordin try

**Comment by swordin** [comment]
> /lac rmpass should work

it works but it causes Java errors (((

**Comment by lenis0012** [comment]
@swordin put them on pastebin and link in here?

**Comment by swordin** [comment]
excuse me, I don't know how to use pastebin

here's the code:




>lac rmpass LAX_555
[16:57:21 ERROR]: Could not pass event AuthModeChangedEvent to LoginSecurity v2.1.6
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot.jar:git-Paper-819]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-Paper-819]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Paper-819]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:175) [LoginSecurity.jar:git-LoginSecurity-cc5768e]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:142) [LoginSecurity.jar:git-LoginSecurity-cc5768e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.getPlayer(CraftServer.java:404) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:401) ~[PaperSpigot.jar:git-Paper-819]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.getPlayer(PlayerSession.java:128) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onAuthChange(PlayerListener.java:156) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot.jar:git-Paper-819]
        ... 9 more
[16:57:21 WARN]: [LoginSecurity] Task #15657 for LoginSecurity v2.1.6 generated an exception
java.lang.NullPointerException
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.modules.command.Command.reply(Command.java:71) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.commands.CommandAdmin.access$000(CommandAdmin.java:28) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.commands.CommandAdmin$1.call(CommandAdmin.java:94) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2$1.run(PlayerSession.java:146) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [PaperSpigot.jar:git-Paper-819]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Tzzzt123** [comment]
Is it a hosted server? Does the host provide official Spigot builds? If yes, then get the official Spigot build instead of using PaperSpigot

**Comment by swordin** [comment]
Yes, it's a hosted server. I'm the hoster. Could you be so kind to explain - where/how can I download the official build?

**Comment by Tzzzt123** [comment]
@swordin i was speaking of a server host that doesn't host it on your pc.
Here is a server host where you can try to get the official Builds: [Server.Pro](https://server.pro)
Step 1: Make an account
Step 2: Click on Create new server
Step 3: Select Spigot1.10 and just create a provisorical server with a random IP.
Step 4: Go to the control panel
Step 5: Click on File Manager
Step 6: Double-Click the Spigot.jar (It's with a version number after the Spigot)
Step 7: Here you've downloaded it

**Comment by swordin** [comment]
No, it's not on my PC - it's really host in the Net. 

And Server.Pro looks like does not suit me. The free version is too small. And the premium version requires monthly payment ;)

**Comment by swordin** [comment]
Aah, I see! I tried and everything turned out! Thank you )

**Comment by Tzzzt123** [comment]
good @swordin

**Comment by lenis0012** [comment]
@Tzzzt123 You recognized that he's running paperspigot from the error?
good lad.

**Comment by lenis0012** [comment]
@swordin @Tzzzt123 So, more importantly.
An issue is, lack of support for Paperspigot?

**Comment by Tzzzt123** [comment]
ask @swordin
My opinion about that (not 100% sure) i think there is a lack of support for paper @lenis0012

**Comment by swordin** [comment]
...anyway, we're waiting for LogSec 2.2 ;)

**Comment by swordin** [comment]
mm... anyway - the error occurs even under the new build: 


>lac rmpass Erwin
[11:33:29 ERROR]: Could not pass event AuthModeChangedEvent to LoginSecurity v2.1.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:175) [LoginSecurity.jar:git-LoginSecurity-cc5768e]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:142) [LoginSecurity.jar:git-LoginSecurity-cc5768e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.getPlayer(CraftServer.java:408) ~[PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:384) ~[PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.getPlayer(PlayerSession.java:128) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.modules.general.PlayerListener.onAuthChange(PlayerListener.java:156) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        ... 8 more
[11:33:30 WARN]: [LoginSecurity] Task #1384 for LoginSecurity v2.1.6 generated an exception
java.lang.NullPointerException
        at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.modules.command.Command.reply(Command.java:71) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.commands.CommandAdmin.access$000(CommandAdmin.java:28) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.commands.CommandAdmin$1.call(CommandAdmin.java:94) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2$1.run(PlayerSession.java:146) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [PaperSpigot.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Tzzzt123** [comment]
you are still using paper...

**Comment by swordin** [comment]
Well, I use the build that I created on this advice:

> Tzzzt123 commented 2 days ago
> ...
> Here is a server host where you can try to get the official Builds: Server.Pro
> Step 1: Make an account
> Step 2: Click on Create new server
> Step 3: Select Spigot1.10 and just create a provisorical server with a random IP.
> Step 4: Go to the control panel
> Step 5: Click on File Manager
> Step 6: Double-Click the Spigot.jar (It's with a version number after the Spigot)
> Step 7: Here you've downloaded it


Did I was wrong?

**Comment by Tzzzt123** [comment]
Nevermind @swordin

**Comment by Tzzzt123** [comment]
@swordin make sure to change the server jar to execute to spigot1.10.jar

**Comment by swordin** [comment]
I'm sure this is 100 percent! My new server jar is built exactly according to your recommendation.

**Comment by swordin** [comment]
...just a loading log:

Loading libraries, please wait...
[18:57:39 INFO]: Starting minecraft server version 1.10
[18:57:40 INFO]: Loading properties
[18:57:40 INFO]: Default game type: SURVIVAL
[18:57:40 INFO]: This server is running CraftBukkit version git-Spigot-6016ac7-10c10b3 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
[18:57:41 INFO]: Server Ping Player Sample Count: 12
[18:57:41 INFO]: Using 4 threads for Netty based IO
[18:57:41 INFO]: Debug logging is disabled
[18:57:41 INFO]: Generating keypair
...
...
...

**Comment by lenis0012** [comment]
@swordin https://yivesmirror.com/downloads/spigot

**Comment by swordin** [comment]
Oops...


Error 522 Ray ID: 3481a6bd7b8e6b0d • 2017-03-31 07:39:19 UTC
Connection timed out



I will try again later...

**Comment by Tzzzt123** [comment]
You are using the good spigot version...

**Comment by swordin** [comment]
Ah, that's right! Thank you )
