### ISSUE TITLE
LoginSecurity 2.1.6:  Failed to read json from url https://api.curseforge.com

### ISSUE THREAD

**Issue by swordin** [lenis0012/LoginSecurity-2#93]
Hello, 

A new strange thing. Could you explain -- what's the problem?

[13:40:39 WARN]: [LoginSecurity] Failed to read json from url https://api.curseforge.com/servermods/files?projectIds=41702
[13:40:39 WARN]: [LoginSecurity] Task #110 for LoginSecurity v2.1.6 generated an exception
java.lang.NullPointerException
        at com.lenis0012.bukkit.loginsecurity.modules.general.GeneralModule$3$1.run(GeneralModule.java:140) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot.jar:git-Paper-819]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [PaperSpigot.jar:git-Paper-819]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [PaperSpigot.jar:git-Paper-819]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Plazmaz** [comment]
At a glance, this looks like an issue with Curse. The URL https://api.curseforge.com/servermods/files?projectIds=41702 returns 
Error 521: Web server is down
as does
https://api.curseforge.com.

**Comment by swordin** [comment]
Thank you so much. 

So, that is, this is a global problem and not just mine?
And we can only wait, do we?

**Comment by lenis0012** [comment]
@swordin is the error gone now?
the url responds properly for me.

**Comment by swordin** [comment]
Mm... I don't know ) I installed the filtering plugin for log-messages that annoy me and no longer see those messages )

**Comment by lenis0012** [comment]
@swordin Perphaps i will make the next version ignore updater errors.
alternatively, you could download your version off of spigotmc, which pulls updates directly off this github project, so you have less downtime and you get the updates sooner.

**Comment by swordin** [comment]
Thank you for your recommendation, but this problem does not bother me anymore. There are more important flaws, due to which I'm looking forward to updating your plugin.
