### ISSUE TITLE
Task #83 NullPointerException

### ISSUE THREAD

**Issue by Shiikii** [lenis0012/LoginSecurity-2#97]
No idea what happend, that showed up in console today, after changing server host ._.

`[23:54:17 WARN]: [LoginSecurity] Task #83 for LoginSecurity v2.1.6 generated an exception
java.lang.NullPointerException
at com.lenis0012.bukkit.loginsecurity.modules.general.GeneralModule$3$1.run(GeneralModule.java:140) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-f950f8e-0fa1ad2]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-f950f8e-0fa1ad2]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [mc.jar:git-Spigot-f950f8e-0fa1ad2]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [mc.jar:git-Spigot-f950f8e-0fa1ad2]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [mc.jar:git-Spigot-f950f8e-0fa1ad2]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [mc.jar:git-Spigot-f950f8e-0fa1ad2]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]`

**Comment by Tzzzt123** [comment]
did you copy the old database?

**Comment by Shiikii** [comment]
Yes I did, I ctrlc ctrlv whole plugin(tried reinstall too)

**Comment by Tzzzt123** [comment]
don't CtrlC ctrlV just copy the database file

**Comment by lenis0012** [comment]
Did you by chance disable the updater or get any errors about it?
Also, did this issue resolve itself?

**Comment by lenis0012** [comment]
Due to the age of this issue, I will close it.
If it still happens, please open a new one
